### ISSUE TITLE
Cannot send a message on SC to all the users to which a nurse can send on HB

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#10]
Steps to reproduce:

1. Log-in on SC with a nurse account
2. Tap on a patient 
3. On the buttons from 'Snapshot' tap on 'Send Messages'
4. Check the users to which the nurse can send a message
5. Login on HB with the same nurse account, click on the same patient and open 'Communications' tab
6. Check the users to which the nurse can send a message

Actual result:

The 'Recipients list' at step 4 is diffrent from the 'Recipients list' at step 6.

Expected result:

The 'recipients list' should be the same on HB and SC

**Note:** If "Reply all" is taped the users that are part of the conversation are added to 'recipients list'. See second screenshot

![recipients_list1](https://cloud.githubusercontent.com/assets/14166590/16167053/91df6162-34f9-11e6-9f01-884d5eee57e4.PNG)
![recipients_list2](https://cloud.githubusercontent.com/assets/14166590/16167052/91df0c08-34f9-11e6-828c-703eabc8275b.PNG)

**Comment by tudorsss** [comment]
Bug already exists: https://envoy.myjetbrains.com/youtrack/issue/SC-109.
