### ISSUE TITLE
HB - Should an updated reminder present the update information on the next repeating days?

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#101]
Steps to reproduce:

1. Have a reminder set for a patient for more then one day;
2. From Dashboard/Reminders update the reminder;
3. The next day check if the new reminder appears as updated in Dashboard/Reminders

Actual result:

3 No, it does not. 

Expected result:

3 It should, shouldn't it?

**Note:** Same goes for items in Dashboar/Ongoing assessment and Dashboard/Initial Assessment

![2016-07-12 15_05_14](https://cloud.githubusercontent.com/assets/14166590/16766325/25c106dc-4842-11e6-93c7-4bf7790c2c90.png)
![2016-07-12 15_06_30](https://cloud.githubusercontent.com/assets/14166590/16766326/25c309be-4842-11e6-9a4f-cb03fd88e9d3.png)

**Comment by tudorsss** [comment]
Good job with this bug @unleu! I am impressed 👍 

https://envoy.myjetbrains.com/youtrack/issue/HB-1447
