### ISSUE TITLE
HB - Portal changes in Dashboard does not get updated

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#102]
Steps to reproduce:

1. Using an admin account go to Dashboard/Portal Changes;
2. Open an item from the list ( if none exists, create one via Patient HB );
3. Check how 'New Data' and ' Reviewed by [] on [] ' is displayed on the screen;

Actual result:

3 The two informations are overlapped as shown in the print screen.

Expected result:

3 They should be displayed separately on the screen.
![2016-07-12 15_18_08](https://cloud.githubusercontent.com/assets/14166590/16766764/98adc020-4844-11e6-954f-6478774d58fc.png)

**Comment by tudorsss** [comment]
https://envoy.myjetbrains.com/youtrack/issue/HB-1446
