### ISSUE TITLE
HB - 500 server error on saving Wound Progress Notes

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#103]
Steps to reproduce:

1. Open a patient's details and navigate to **Nursing/Wound Progress** Notes subsection;
2. Click on 'Add row', fill out the required fields and save it;
3. Try and save Wound Progress Note and see if information gets saved;

Actual result:

3 500 Server error shows up when trying to save.

Expected result:

3 No error should occur when trying to save Wound Progress Notes.

Request URL:https://test.envoymobile.net/api/form/checklist_wound/
Request Method:POST
Request Payload: 

```
{
  "wounds": [
    {
      "location": "wound location",
      "length": 15,
      "width": 15,
      "depth": 22,
      "drainage": "No",
      "stage": "3",
      "eschar": "No",
      "slough": "No",
      "inflammation": "No",
      "undermining": "No",
      "treatment": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. N",
      "comment": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. N",
      "intake_id": "46",
      "patient_id": "42",
      "updated_by": "Paul Cooper (pcoop)",
      "updated_on": "07/12/2016 20:44:33"
    }
  ],
  "intake_id": "46",
  "patient_id": "42"
}
```

Response Payload:

{"trace": "Traceback (most recent call last):\n  File \"/opt/envoy/hbd/local/lib/python2.7/site-packages/flask/app.py\", line 1639, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/opt/envoy/hbd/local/lib/python2.7/site-packages/flask/app.py\", line 1625, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/opt/envoy/hbd/local/lib/python2.7/site-packages/flask/views.py\", line 84, in view\n    return self.dispatch_request(*args, **kwargs)\n  File \"/opt/envoy/hbd/local/lib/python2.7/site-packages/flask/views.py\", line 149, in dispatch_request\n    return meth(*args, **kwargs)\n  File \"/opt/envoy/hbd/local/lib/python2.7/site-packages/envoyd/auth.py\", line 201, in decorated\n    return f(*args, **kwargs)\n  File \"/opt/envoy/hbd/local/lib/python2.7/site-packages/envoyd/validators/http_basic.py\", line 18, in decorated\n    return f(*args, **kwargs)\n  File \"/opt/envoy/hbd/local/lib/python2.7/site-packages/envoyd/middleware/jsonpv.py\", line 8, in decorated\n    result = f(*args, **kwargs)\n  File \"/opt/envoy/hbd/hbd/form/views.py\", line 338, in post\n    return creq(self._action, form_id)\n  File \"/opt/envoy/hbd/hbd/form/views.py\", line 231, in __call__\n    return self.create(form_id)\n  File \"/opt/envoy/hbd/hbd/form/views.py\", line 86, in create\n    abort(500, e)\n  File \"/opt/envoy/hbd/local/lib/python2.7/site-packages/werkzeug/exceptions.py\", line 646, in __call__\n    raise self.mapping[code](*args, **kwargs)\nInternalServerError: 500: Internal Server Error\n", "error": "(psycopg2.DataError) invalid input syntax for integer: \"Paul Cooper (pcoop)\"\nLINE 1: ...mestamp, '2016-07-12T20:44:49.809389'::timestamp, 'Paul Coop...\n                                                             ^\n [SQL: 'INSERT INTO form_checklist_wound_details (created_on, change_on, updated_by, archived, created_by, auto_name, change_type, change_by, deleted, updated_on, change_data, comment, undermining, depth, width, inflammation, slough, treatment, stage, eschar, location, length, drainage, intake_id, patient_id, reviewed_by, reviewed_on) VALUES (%(created_on)s, %(change_on)s, %(updated_by)s, %(archived)s, %(created_by)s, %(auto_name)s, %(change_type)s, %(change_by)s, %(deleted)s, %(updated_on)s, %(change_data)s, %(comment)s, %(undermining)s, %(depth)s, %(width)s, %(inflammation)s, %(slough)s, %(treatment)s, %(stage)s, %(eschar)s, %(location)s, %(length)s, %(drainage)s, %(intake_id)s, %(patient_id)s, %(reviewed_by)s, %(reviewed_on)s) RETURNING form_checklist_wound_details.id'] [parameters: {'comment': u'Lorem ipsum dolor sit amet, consectetur adipiscing elit. N', 'reviewed_by': None, 'undermining': u'No', 'created_on': datetime.datetime(2016, 7, 12, 20, 44, 49, 809361), 'change_on': datetime.datetime(2016, 7, 12, 20, 44, 49, 809389), 'updated_by': u'Paul Cooper (pcoop)', 'archived': False, 'treatment': u'Lorem ipsum dolor sit amet, consectetur adipiscing elit. N', 'created_by': 137, 'auto_name': None, 'width': Decimal('15.00'), 'location': u'wound location', 'slough': u'No', 'length': Decimal('15.00'), 'intake_id': u'46', 'inflammation': u'No', 'change_type': None, 'change_by': None, 'deleted': False, 'stage': u'3', 'eschar': u'No', 'patient_id': u'42', 'depth': Decimal('22.00'), 'reviewed_on': datetime.datetime(2016, 7, 12, 20, 44, 49, 809606), 'drainage': u'No', 'updated_on': datetime.datetime(2016, 7, 12, 20, 44, 33), 'change_data': 'null'}]"}

![2016-07-13 00_01_54](https://cloud.githubusercontent.com/assets/14166590/16783473/d2cc1912-488c-11e6-83cb-fe7c5764edb0.png)

**Comment by tudorsss** [comment]
Hey @unleu,

This bug is no longer happening on my side; I tested with two patients, as an admin user. Vlad Badea and Amanda Blackwell. Please let me know what you find out.

Thanks!
