### ISSUE TITLE
Warning message on adding supplies

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#11]
Steps to reproduce

1. Login to SC with a valid nurse account
2. Tap on a patient. Make sure the patient has an active treatment
3. Tap on the menu button and select 'Supplies'
4. Add new supply
5. From 'Supply Bundle' drop down list select one bundle

Actual result:

A warning message appears as in the screen shot attached

Expected result:

This message should not appear. On HB this message does not pop up.

![screenshot_supplie_items](https://cloud.githubusercontent.com/assets/14166590/16167004/02039f72-34f9-11e6-8021-660860e3a414.PNG)

**Comment by tudorsss** [comment]
Hey @unleu,

This is no longer happening on the latest SC build. Can you take another look? I tested with smyers as a nurse and used Allview Jana as a patient.

**Comment by tudorsss** [comment]
I added two new bugs related to this though.

**Comment by unleu** [comment]
@tudorsss true, it's gone :)
