### ISSUE TITLE
Syncing closes the patient's dashboard

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#12]
Steps to reproduce:

1. Login to SC with a valid nurse account;
2. Open the records of all of your patients;
3. With or without making a change in one of the forms (you can have a few forms opened) go to Menu and tap on 'Sync';
4. Select 'Sync' button and wait for syncing to complete;
5. Check behavior in regards to the patient records;

Actual result:

5. The app closes the patient's dashboard and after sync is reopened at the patients list, even if you had open forms on some patients.

Expected result:

5. Syncing should not affect the state the app was before the sync.

**Comment by tudorsss** [comment]
I don't think this is a bug. What are your arguments?

**Comment by unleu** [comment]
@tudorsss It can be a problem when a form is being filled by the user and in the process he has to sync something else. Else, it may not be a problem except for the waiting time for reopening the patient's record.

**Comment by unleu** [comment]
or when I have 5 patients open, each on different subsections and after syncing all close and reopening is a very annoying and time wasting process

**Comment by tudorsss** [comment]
Hey @unleu,

I updated your bug; please add it as a Critical in the SC project; assign it to Chirag.

**Comment by unleu** [comment]
https://envoy.myjetbrains.com/youtrack/issue/SC-134
