### ISSUE TITLE
SC - Sending a message from SC while the ipad is connected to the internet does not work

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#19]
Steps to reproduce:

1. Login to SC with a valid nurse account. Make sure your tablet is connected to the internet.
2. Tap on a patient name and from the quick access buttons tap on 'Send a message'
3. Select one/more users, write a message and send it.
4. On the user/users account, check immediately if he/they received the message.

Actual result:

The message was not sent

Expected result:

As long as the tablet is connected to the internet Communications should work without syncing.

**Note: When manual syncing the message is immediately sent.**

**Comment by unleu** [comment]
@tudorsss I'll retest it to see if it works in that 1 hour time Patrick mentioned. If it indeed works and the message is sent after, let's say, 45 min, in my opinion, it is still a bug.

**Comment by tudorsss** [comment]
@unleu, any updates?

**Comment by unleu** [comment]
message did not arrive without manual sync
