### ISSUE TITLE
Archiving on SC when no internet connection

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#21]
Steps to reproduce:

1. Login to SC with a valid nurse account
2. Tap on a patient name and go to 'Main Menu'
3. Go to any of the following: Allergies, Medications, lab results. Make sure there is at least one item in the list that you can archive. 
4. Open the item and tap on 'Archive'
5. Now tap on 'Main Menu' button and see at Sync ( what number is shown on the blue circle background ).
6. Tap on 'Sync' and check behavior.
7. After connecting to the internet tap on 'Sync' button and wait for sync. 
8. Check how the items appear on SC on every category at step 3
9. Check on HB if items were synced

Actual result:

5. If the user archived 5 items number 5 is shown on the blue circle background - check screen shot
6. No forms are shown in 'Sync data: Pending Upload' 
8. The items appear 'Unsynced' - check screen shot
9. Syncing did not work. No forms are archived. 

Expected result:

6. There should be 5 forms in the list to sync.
8. Forms should have been synced

**Note:** Test reproduced on an item on Supplies with the following result: steps 1-8 above are reproduced exactly. Despite steps 1-8 the syncing worked.
**Note:** Syncing works if after step 8, on SC and while connected to the internet, you tap on that item and archive it again.
@tudorsss At step 3, should i test on every possible situation ?

**Comment by tudorsss** [comment]
https://leantesting.com/en/projects/envoy-scout/16582/bug/1
