### ISSUE TITLE
HB/SC - 'Find' on 'Wound progress note' does not work. 

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#22]
Steps to reproduce:

1. Login to SC with a valid nurse account
2. Tap on a patient name and go to 'Main Menu'
3. Go to 'Nursing' -> 'Wound progress note'
4. Tap on 'Find'
5. Check behavior

Actual result:

5. The app opens an 'Add new' form for ' Wound progress note'

Expected result:

5. The search should not lead you to 'Add new' items

**Comment by tudorsss** [comment]
https://envoy.myjetbrains.com/youtrack/issue/HB-1256
