### ISSUE TITLE
HB/SC - Cannot view list of 'Wound progress note' & Lack of 'List' button

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#23]
Preconditions: Use a patient with an active treatment and a wound progress note added

Steps to reproduce:

1. Login to HB with a valid user account
2. Open a patient's record. Make sure he has an active treatment.
3. Go to 'Nursing' and click on 'Wound progress note'
4. Check behavior
5. Now click on 'Edit' and with or without changes 'Save' changes
6. Check behavior
7. Click on 'Add new' button, complete the required fields and click on 'Save'
8. Close the patient's record and reopen it. Reproduce step 2-4
9. Check behavior

Actual result:
4. The app directly opens a wound progress note. Notice that there is no button 'LIST'. 
6. Now a list with all wound progress notes is opened. 
9. The firstly added 'Wound progress note' is opened. 

Expected result:

4 . The app should open at the list of wound progress notes. 
6 . While viewing a wound progress note's details there should be a 'List' button that would get the user back to viewing all of the wound progress notes
9 . The list with all progress notes should be opened.

**Comment by tudorsss** [comment]
Hey @unleu,

Here there are multiple bugs; we should separate them into multiple tickets:

- https://envoy.myjetbrains.com/youtrack/issue/HB-1248
- https://envoy.myjetbrains.com/youtrack/issue/HB-1254
- https://envoy.myjetbrains.com/youtrack/issue/HB-1255

Let me know what you think.

**Comment by unleu** [comment]
they are OK. for bug HB 1253, the thing is about every form without required fields can be saved without filling any data. Should we crate multiple issues or 1 for all ?
