### ISSUE TITLE
CSR user can archive a 'Care Plan'

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#24]
Preconditions: make sure that the patient you are using has an active treatment and an open Care Plan

Steps to reproduce:

1. Log in to HB with a valid admin account, on test.envoymobile.net;
2. Go to **Patients** & get into the above patient's details;
3. Go into the **Nursing** subsection;
4. Select **Care Plan**;
5. Try and archive the **Care Plan**;
6. Check behavior;

Actual result:

The user is allowed to archive the Care Plan

Expected result:

The CSR user should not be allowed to archive a Care Plan. 

**Patient > Intake > Care Plan**

model:
	access:
		create:     ['admin', 'csr', 'nurse', 'pharm']
		**delete:     ['admin', 'pharm', 'nurse']**
		read:       ['admin', 'csr', 'nurse', 'patient', 'pharm', 'physician']
		read_all:   ['admin', 'csr', 'nurse', 'patient', 'pharm', 'physician']
		request:    []
		update:     []
		update_all: ['admin', 'csr', 'nurse', 'pharm']
		write:      ['admin', 'csr', 'nurse', 'pharm']

**Comment by tudorsss** [comment]
Hey @unleu, 

Is this still happening?

**Comment by unleu** [comment]
@tudorsss yes.

**Comment by tudorsss** [comment]
But @unleu, this is now duplicated by https://envoy.myjetbrains.com/youtrack/issue/HB-1363 so we don't need it anymore.

I'm going to close it, let me know if I am wrong.
