### ISSUE TITLE
In Dashboard mode, a pharmacist cannot mark as 'Done' needs review items

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#32]
In relationship with https://envoy.myjetbrains.com/youtrack/issue/HB-1302 

If a needs review item is assigned to a pharmacist he cannot mark it as Done. If an admin assigns a pharmacist to deal with a 'needs review' form he should also be able to Close it, not only update it.

Preconditions:
 have an admin account;
 have a pharmacist account;
 have a patient account that has access to the portal
 use dev.envoymobile.net;

Steps to reproduce:

1. Login to dev with the patient account;
2. Create or update patient history form and self-assessment form
3. Add new allergy and new medication 
4. Logout and login to dev with the admin account
5. Navigate to the Dashboard/Needs Review sub-section;
4. Open each of the items created/updated for that patient and assign them the above pharmacist;
6. Logout and login to dev with the pharmacist account; 
7. Go to Dashboard at Needs Initial Assessment;
8. Open the related alert(s) and try to select Done and Save them;

Actual result:

8. The pharmacist cannot mark this alerts as Done;

Expected result:

8. The pharmacist assigned should be able to not only update an item in needs review but to also mark it as Done when finished.

**Comment by tudorsss** [comment]
http://pm.envoymobile.com/youtrack/issue/HB-1317
