### ISSUE TITLE
Schedule for initial assessment is not shown in Dashboard/Task subsection

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#34]
When scheduling for an initial assessment the task should appear in Dashboard, but it does not.

Steps to reproduce:

Log in as an admin user on dev.envoymobile.net;
Go to a patient's details;
Open 'Treatment'/'Schedule Follow Up' and add new 'Initial Assessment' schedule event
Navigate to Dashboard/Task and see if you can see the new task

Actual results:
4. No, you do not.

Expected result:
4. Yes, you should.

**Comment by tudorsss** [comment]
http://pm.envoymobile.com/youtrack/issue/HB-1297
