### ISSUE TITLE
A pharmacist cannot view portal changes like medication or allergies in Dashboard

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#35]
A pharmacist should be able to see and review, in Portal Changes, a new allergy or medication added by his patient.

Steps to reproduce:

1. Login to dev with the patient account;
2. In the main menu go to Medication or Allergy
3. Add new allergy and new medication
4. Logout and login to dev with the admin account
5. Navigate to the Dashboard/Portal Changes sub-section;
6. Check if you can see the new changes in the list
7. Logout and login to dev with the pharmacist account;
8. Go to Dashboard/Portal Changes sub-section;
9. Check if you can see the new changes in the list

Actual result:
6. The admin user can see the new allergy or medication in portal changes
9. The patient's pharmacist cannot see the new allergy or medication in portal changes.

Expected result:

The pharmacist should be able to see and approve or reject the new allergy or medication.

**Comment by tudorsss** [comment]
http://pm.envoymobile.com/youtrack/issue/HB-1315
