### ISSUE TITLE
not bugs..

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#36]
- when rejecting a portal change the possibility to motivate the rejection should be offered
- the possibility to schedule a ONE TIME only reminder should be offered

**Comment by tudorsss** [comment]
The first bullet is a feature; there are a lot of bugs to fix so this feature won't worth it right now. I don't understand the second bullet; don't you have that in the schedule follow-up? are you saying that you want a daily breakdown, a repeating reminder and a one-time reminder too?

You can set your repeating reminder not to repeat, right?

**Comment by unleu** [comment]
@tudorsss yep, didn't think like that :)
