### ISSUE TITLE
Reminders don't show up in Dashboard

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#37]
A simple reminder created by an admin or pharmacist does not show up in Dashboard/Reminder

Preconditions:
have an admin account;
have a pharmacist account;
use dev.envoymobile.net;

Steps to reproduce:

1. Login with either an admin or a pharmacist account
2. Go to the a patient's details
3. At Treatment select Schedule Follow-up
4. Add new schedule with event type 'Reminder'. 
5. Navigate to Dashboard/Reminder subsection and see if the reminder shows up.

Actual result:

5. No, it does not.

Expected result:

5. It should.

**Comment by tudorsss** [comment]
This was already added, http://pm.envoymobile.com/youtrack/issue/HB-1297.
