### ISSUE TITLE
A pharmacist cannot assign a 'Schedule Follow Up'

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#38]
While creating a scheduled event via Schedule Follow Up a pharmacist cannot assign it to another user .

Steps to reproduce:

1. Login with a pharmacist account on dev.envoymobile.net
2. Go to a patient's details
3. Open Treatment/Schedule Follow Up
4. Select Add new
5. Try and select a user from 'Assigned User(s)'

Actual result:

No results are found on the  'Assigned User(s)' dropdown list

Expected result:

The list should contain users so that the scheduled event could be assigned

**Comment by tudorsss** [comment]
http://pm.envoymobile.com/youtrack/issue/HB-1316
