### ISSUE TITLE
Have to explain the difference between Approved in Portal Changes and Reviewed

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#39]
1. I approved an allergy but the field 'reviewed by' showed nothing and the field 'reviewed on' showed the time/date the patient created the form.
2. the field 'status' is missing from allergies
3. I approved a medication but the fields 'reviewed by' and 'status' showed nothing and the field 'reviewed on' showed the time/date the patient created the form.
4. After being approved The user can Review the allergy or the medication. What is the diffrence ? Approve should be equivalent to reviewed on 'Reviewed by/on' field.
5. After being reviewed the information is showed in the fields above mentioned.

**Comment by tudorsss** [comment]
Portal changes items should not show up in needs review after they've been approved. I added a bug on youtrack, so I'll close this one out.
