### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#46]
1. Shouldn't Care Plan be reviewed ?
2. What does **Reported By** field in medications mean ? The only options are Patient reported and Physician reported. 'The problem' is that a Pharmacist, nurse or admin could save a medication.
3. A nurse should only be able to see the patients that are assigned to her, right ? Or at least her patients should have a mark so that the nurse knows who her patients are. In the current state, a nurse can view or modify any patient, but then what is the purpose of assigning a patient to a nurse ?
4. A search option for users in Communications would be useful

**Comment by tudorsss** [comment]
1: https://envoy.myjetbrains.com/youtrack/issue/HB-1357?query=sort+by%3A+Created

**Comment by tudorsss** [comment]
2. https://envoy.myjetbrains.com/youtrack/issue/HB-1358

**Comment by tudorsss** [comment]
Hey @unleu, at 3 . , where do you assign the nurse for the patient? In SC the nurse only sees the patients scheduled for her.

**Comment by tudorsss** [comment]
4 . is a feature; it's not so important right now

**Comment by unleu** [comment]
@tudorsss at no. 3 I was referring to HB. In HB everybody can see all the users. But for a doctor/pharmacist/nurse can be confusing not to know which users are assigned to you and which are not.

**Comment by tudorsss** [comment]
We got an answer from Patrick related to what a nurse should do: a nurse should have access to all patients.

Based on this, I think we can close this ticket out.
