### ISSUE TITLE
502 Bad Gateway - Analytics is not loading

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#47]
Steps to reproduce:
1. Login to HB with a valid **pharmacist, nurse or physician** account;
2. Open **'Analytics'** and check behavior;

Actual result:

2. The page is continuously loading;

Expected result:

2. Analytics page should load and show data.

GET Request URL:
`{code}https://dev.envoymobile.net/api/report/therapy/ivig/{code}`

Response payload:
```
{code}<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
{code}
```

**Comment by tudorsss** [comment]
Hey @unleu,

This bug is not happening for me. Something else is the problem here:

![screen shot 2016-06-28 at 11 48 02](https://cloud.githubusercontent.com/assets/12154831/16409438/3a74efc0-3d26-11e6-8684-342db947c881.png)

Can you take another look?

**Comment by unleu** [comment]
@tudorsss is not happening to me either today. I'll take a closer look later.

**Comment by unleu** [comment]
@tudorsss this is not happening for an ADMIN user. 

Reproduced it with a pharmacist account.

**Comment by tudorsss** [comment]
Hey @unleu,

See what other user roles are experiencing this problem and then let's add the bug to Youtrack. Use Critical as the priority.

**Comment by unleu** [comment]
https://envoy.myjetbrains.com/youtrack/issue/HB-1364

**Comment by unleu** [comment]
@tudorsss it is happening on test.envoy; pls check
