### ISSUE TITLE
401 Unauthorized - Pharmacist cannot assign a 'Needs Review' item

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#49]
Steps to reproduce:

1. Use a pharmacist account and navigate to 'Dashboard'/'Needs review' subsection
2. Open a needs review item and try to assign it to another user

Actual result:

2. No user are found in the drop down list 'Assigned to'

Expected result:

2. The pharmacist should be able to assign a needs review item.

GET Request URL:  
`
{code}URL:https://dev.envoymobile.net/api/form/permission_group/?fields=min&sort=auto_name&limit=100&
{code}
`

Query string parameteres: 
`{code}fields=min&sort=auto_name&limit=100&{code}`

Response payload:` {code}{"error": "Permission denied"}{code}`

**Comment by tudorsss** [comment]
Hello @unleu,

The actual and expected result are 2. not 1. In the expected result, please add:

If the pharmacist is not allowed to do this, should he be given the option?

Other than that, please add the bug to youtrack.

**Comment by unleu** [comment]
@tudorsss i know, but GitHub sucks, it makes them all 1 if I put '.' after a number

**Comment by tudorsss** [comment]
https://envoy.myjetbrains.com/youtrack/issue/HB-1353
