### ISSUE TITLE
All read-only forms that support 'Reviewed' display the wrong static message at the top

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#50]
Preconditions:
This bug is reproduced on all type of forms that can be Reviewed and only the first time you create a new item.

Steps to reproduce:

1. Open the patient's record and navigate to one of the Subsections that is relevant ( eg: Medications, Allergy, History, Nursing Visit Notes );
2. Click on 'Add new', make sure all the required fields are filled out and save information;
3. Check what is displayed at the top of the read-only form;

Actual result:

3 . The following message is displayed:
REVIEWED BY N/A ON JUN 28, 2016 10:07:20 AM

Expected result:

3 . 'Pending review' message should be displayed

**Note:** After editing the item the correct message is displayed: 'Pending review' .

**Comment by tudorsss** [comment]
Hey @unleu,

This happens for all of the forms that need to be reviewed. Please update it accordingly.

**Comment by unleu** [comment]
@tudorsss updated

**Comment by tudorsss** [comment]
Looks good @unleu, please add it in Github.
