### ISSUE TITLE
401 Unauthorized when refreshing 'Portal Changes' as a pharmacist

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#51]
Steps to reproduce:

1. Use a pharmacist account and navigate to "Dashboard'/'Portal Changes' subsection;
2. Click on 'Refresh' button - use developer tools;

Actual result:

2 No error message is displayed but 401 Unauthorized error occurs.

Expected result:

2 A pharmacist should be able to view  'Portal Changes'.

GET Request URL:
`{code}https://dev.envoymobile.net/api/form/changeset/?sort=id&filter=status:null{code}`

Query string parameters:
`{code}sort=id&filter=status:null{code}`

Response payload:
`{code}{"error": "Permission denied"}{code}`

**Comment by tudorsss** [comment]
Hey @unleu,

The steps to reproduce don't say with whom do we need to log in, the actual result is missing the 2. indicator and there is no expected result.

Please update the bug.

**Comment by tudorsss** [comment]
Added some punctuation but in rest the bug is good to get added in Youtrack. Add it as a major priority.

**Comment by unleu** [comment]
added 

https://envoy.myjetbrains.com/youtrack/issue/HB-1356
