### ISSUE TITLE
Reviewed by field is shown if no review was made on 'Nursing visit notes' form

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#52]
Preconditions:
Make sure you use a patient with an active treatment.

Steps to reproduce:

1. Open the patient's record and navigate to 'Nursing'/'Nursing visit notes'
2. Add new nursing note, fill out the required fields, click on Save and check what is displayed about reviewing the form
Actual result:

The following message is displayed: REVIEWED BY N/A ON JUN 28, 2016 10:33:51 AM

Expected result:

'Pending review' message should be displayed

**Comment by tudorsss** [comment]
This is the same as bug #50, I'm going to close it out.
