### ISSUE TITLE
Needs review - 28.06.2016

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#53]
1 https://envoy.myjetbrains.com/youtrack/issue/HB-1342 

**fixed**

2 https://envoy.myjetbrains.com/youtrack/issue/HB-1317

**fixed** 

3 https://envoy.myjetbrains.com/youtrack/issue/HB-1311

**almost fixed**
You have a review button and after clicking it the following info is displayed:
_REVIEWED BY PAUL COOPER ON JUN 28, 2016 9:58:25 AM_

* If no review is made the following message appears:
REVIEWED BY N/A ON JUN 28, 2016 10:07:20 AM - posted bug https://github.com/tudorsss/Food-Tracker/issues/50

4 https://envoy.myjetbrains.com/youtrack/issue/HB-1300
**fixed** for the most part. 
Check https://github.com/tudorsss/Food-Tracker/issues/48 and https://github.com/tudorsss/Food-Tracker/issues/51

5  https://envoy.myjetbrains.com/youtrack/issue/HB-1299

**not fixed**

Note: Is fixed on Pharmacist Initial Assessment. But on Nursing assessment you cand still add more.

6 https://envoy.myjetbrains.com/youtrack/issue/HB-1272

**not fixed**

7 https://envoy.myjetbrains.com/youtrack/issue/HB-1301

**almost fixed**

Check https://github.com/tudorsss/Food-Tracker/issues/52 

8 https://envoy.myjetbrains.com/youtrack/issue/HB-1298

still, cannot find paul cooper, lucy or anybody created by us.

created a physician account and a nurse account but cannot find them in schedule follow-up

**Comment by tudorsss** [comment]
Okay, I worked on the tickets too, thanks for the assistance; I'm going to close it out.
