### ISSUE TITLE
Should there be any restriction set depending on 'Patient Chart Status'?

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#56]
For example:

A patient marked as Deceased can log-in to its account.
An intake form can be created to a Pending patient. 
etc.

**Comment by tudorsss** [comment]
add this bug also the way you wrote it here, assign it to Patrick; add a low priority to it.

**Comment by unleu** [comment]
https://envoy.myjetbrains.com/youtrack/issue/HB-1362
