### ISSUE TITLE
Cannot see the name of the sender if the login username is the email address

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#57]
Steps to reproduce:

1. Create a new patient via 'Patients'/'Add new' and then proceed to login to his portal account (make the patient's username his email address);
2. Send a message to a user;
3. Check the receiver's side message;

Actual result:

3 . On the receiver's side, instead of the patient's name,  '()' is displayed.

Expected result:

3 . The display name should be shown here no matter what username the patient has.

**Comment by tudorsss** [comment]
I'm investigating this but it looks like it's more complicated than it seems at first. I'll continue tomorrow.
