### ISSUE TITLE
1/1/1970 is displayed on the patient's home screen for Past Activity, when completing a Form

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#58]
Steps to reproduce:

1. Login with a patient's account and go to Forms;
2. Add new form and save it;
3. Navigate to 'Home' and check 'Past activity';

Actual result:

3 The date of completing the form is 1 January;

Expected result:

3 There should be the date when the form was created/updated.

**Note:** The date appears to be 1/1/1970, as shown when opening a report from 'Past Activity'

**Comment by tudorsss** [comment]
We have another bug here in which you need to refresh the page to see the changes in step 3. Add that in a separate bug. Priority Critical, add it to Youtrack.

**Comment by tudorsss** [comment]
@unleu ^

**Comment by unleu** [comment]
https://envoy.myjetbrains.com/youtrack/issue/HB-1365
