### ISSUE TITLE
CSR user can edit everything under Nursing section

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#59]
Steps to reproduce:

1. Login with a valid CSR account, open a patient's record (with an active treatment) and navigate to the **'Nursing'** section;
2. Try to add, edit or archive any of the subsections and see if you can;

Actual result:

2 Yes, a CSR user can add, edit or archive any items in the **Nursing** subsections.

Expected result:

2 No, a CSR user should not be able to add/edit/archive anything under **Nursing**.

**Comment by tudorsss** [comment]
I updated it a little, add it too @unleu.

**Comment by unleu** [comment]
https://envoy.myjetbrains.com/youtrack/issue/HB-1363
