### ISSUE TITLE
CSR user can add, edit or archive Pharmacist Ongoing Assessment

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#60]
Steps to reproduce:

1. Login with a valid CSR account and navigate to **'Pharmacist Assessment'/' Ongoing'** subsection
2. Try and add a new **Ongoing assessment** form. See if the information gets saved. 

Actual result:

2 Yes, the **ongoing assessment** is created

Expected result:

2 A CSR user should not be able to create or edit any **Ongoing Assessment** forms

**Comment by unleu** [comment]
@tudorsss At Pharmacist initial assessment there is an EDIT button but when saving you get 'Access denied' error. Should I post a bug about the presence of the EDIT button ?

**Comment by tudorsss** [comment]
Yes @unleu

**Comment by tudorsss** [comment]
And you can add this bug to youtrack too; Add it as a major priority? What do you think?

**Comment by unleu** [comment]
Yep, major it is

**Comment by unleu** [comment]
https://envoy.myjetbrains.com/youtrack/issue/HB-1361
