### ISSUE TITLE
New form for a patient is shown in "Past Activity" only after logging in again

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#61]
Steps to reproduce:

1. Login with a patient's account and go to **Forms**;
2. Add new form and save it;
3. Navigate to **Home** and check if in **Past activity** the newly created form appears;

Actual result:

3 No, the form does not appear. You have to log out and log back in to view the updates; this is counterintuitive.

Expected result:

3 The form should appear after adding it, or a refresh button should be presented in the "past activity" section so that the patient knows that "past activity" doesn't reload by itself.

**Comment by tudorsss** [comment]
Hey @unleu, see what other information should show up in activity and verify that it happens the same as it happens with Form too.

**Comment by unleu** [comment]
@tudorsss the only thing that can be updated are the diagnostic and treatment in the right part of the home screen and Upcoming events. 

Diagnostic and treatment are not auto-refreshed.

The thing is I don't know what upcoming events should be. It should be some kind of a schedule so I created a scheduled from the admin account ( Patient->Patient Reported->Schedule ) but it did not show up on the home screen of the patient. Besides that, there is a button **'Things to do 0 upcoming'** that leads you to forms. So i really don't know what Upcoming events might be.

**Comment by unleu** [comment]
there is also the assigned nurse/doctor/pharmacist. they don't auto-refresh either.

**Comment by tudorsss** [comment]
Hey @unleu,

1. For this update this bug:
-  the only thing that can be updated are the diagnostic and treatment in the right part of the home screen and Upcoming events.

Diagnostic and treatment are not auto-refreshed they are updated upon reload.

2. For this add a new bug:

It should be some kind of a schedule so I created a scheduled from the admin account ( Patient->Patient Reported->Schedule ) but it did not show up on the home screen of the patient. 

3. For this, add a new bug too:

here is a button 'Things to do 0 upcoming' that leads you to forms. So I really don't know what Upcoming events might be.

**Comment by unleu** [comment]
@tudorsss I'm having trouble viewing the Home Screen of a patient for the majority of my patients. Have to figure out why and then i'll create the above bugs

**Comment by unleu** [comment]
@tudorsss 
Diagnostic and treatment are not auto-refreshed they are updated upon reload.

is this really a bug? 

the home screen of a patient does not have refresh button and it does not have auto refresh so how could the diagnosis be refreshed, but on realod/relogin ?

**Comment by unleu** [comment]
@tudorsss first bug https://envoy.myjetbrains.com/youtrack/issue/HB-1375
