### ISSUE TITLE
404 Not Found error when opening Schedule Follow up

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#62]
Maybe in relation with https://envoy.myjetbrains.com/youtrack/issue/HB-1297

Get request URL: https://dev.envoymobile.net/api/form/followupprogram/null

Response payload: {"error": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."}

**Comment by tudorsss** [comment]
Hey @unleu, it works for me; I went into Harold Smith, Treatment/Schedule Follow-up. Can you take another look?

**Comment by unleu** [comment]
@tudorsss it works for me too, but a 404 error occurs ( check developer tools ) when opening and I thought it might be related to HB1297.

not sure if this is a bug, that's why i did not write it down completely

**Comment by tudorsss** [comment]
Got it @unleu, https://envoy.myjetbrains.com/youtrack/issue/HB-1366.
