### ISSUE TITLE
SC - Different columns in  the Medications list on SC and HB

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#64]
Steps to reproduce:

1. Login to SC and HB, open a patient's record and navigate to **Medications**;
2. See if the table head contains the same columns;

Actual result:

In addition to SC on HB there are the fields: **Created On, Status, Revied by and Revied On**.

Expected result:

The table head on SC and HB at Medications should be the same.

**Comment by tudorsss** [comment]
Hey @unleu, below is the updated bug. I am fairly certain that this bug shows up in a lot more sections in the SC app, but we have an older version of the SC app. I asked Patrick to provide a new version and we'll test on that later today.

Steps to reproduce:

1. Login to SC and HB, open a patient's record and navigate to **Medications**;
2. Check if the table head contains the same columns;

Actual result:

2 . In addition to SC on HB there are the fields: **Created On, Status, Reviewed by and Reviewed On**.

Expected result:

2 . The table head on SC and HB at Medications should be the same.

**Comment by tudorsss** [comment]
Bump for @unleu.

**Comment by tudorsss** [comment]
Hey @unleu,

I took screen-shots with all of the differences between a nurse and an admin. Notice the archive is missing in some sections for example. Please create a list of these (preferably a table, but tables don't work in Github except if you use this, http://www.tablesgenerator.com/markdown_tables - it will look the same in Youtrack too).

The shots are in the archive below.

[Admin vs Nurse.zip](https://github.com/tudorsss/Food-Tracker/files/340455/Admin.vs.Nurse.zip)

**Comment by unleu** [comment]
@tudorsss Here is the table you requested

| Nurse                                                                                                                                  | Administrator                                                                                                                                                          |
|----------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Search bar contains: First Name, Last Name, Date of Birth, SSN, Street, Zip and Patients Chart                                         | Search bar contains: First Name, Last Name, Date of Birth, SSN, Street, Zip, Patients Chart, Priority Level,  Site and External ID                                     |
| Nurse does not have ADD NEW button in: Patient, Insurance, Intake, Ongoing Assessment, Dietitian Assessment, Self reported Assessments |                                                                                                                                                                        |
| Search bar does not contain Archive drop down at Patient/Insurance subsection                                                          | Search bar has Archive drop down list at Patient/Insurance subsection                                                                                                  |
| List columns in Patient/Medication subsection are: Medication Name, Medication Dose, Medication Frequency, Reported by                 | List columns in Patient/Medication subsection are: Created by, Medication Name, Medication Dose, Medication Frequency, Reported by, Status, Reviewed by and Reviewd On |
| Search bar in Patient/Medication has only Medication Name drop down list                                                               | Search bar in Patient/Medication has: Medication Name, Associated Condition, Status and Archive drop down lists,                                                       |
| Intake Search field does not contain Archive drop down list                                                                            | Intake Search field contains Archive drop down list                                                                                                                    |
| Pharmacist Initial assessment leads you to a list                                                                                      | Pharmacist Initial assessment leads you to create new assessment or view initial assessment                                                                            |
| No Prefill button in Ongoing Assessment, Dietitian Assessment, Self reported Assessments                                               |                                                                                                                                                                        |
| List columns in Patient contain: Last Name, First Name, Middle name, Date of birth, Street, City, Zip,                                 | List columns in Patient contain: External ID, Last Name, First Name, Middle name, Date of birth, Street, City, Zip, Priority Level                                     |
|                                                                                                                                        |                                                                                                                                                                        |
|                                                                                                                                        |                                                                                                                                                                        |
|                                                                                                                                        |                                                                                                                                                                        |
|                                                                                                                                        |                                                                                                                                                                        |
|                                                                                                                                        |                                                                                                                                                                        |
