### ISSUE TITLE
'Progress Notes' is part of the 'Patient' section on HB and part of the 'Nursing' section on SC

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#65]
Steps to reproduce:

1. Open a patient's record on HB and SC and see where **Progress Notes** subsection is displayed. 

Actual result:

1 On HB **Progress Notes** is displayed under **'Patient'** section
1 ON SC **Progress Notes** is displayed under **'Nursing'** section

Expected result:

**Progress Notes** should be displayed under the same section both on SC and HB.

**Comment by tudorsss** [comment]
Steps to reproduce:

1. Open a patient's record on HB and SC and see where **Progress Notes** subsection is displayed. 

Actual result:

1 . Inconsistency is created: On HB **Progress Notes** is displayed under **'Patient'** section but On SC **Progress Notes** is displayed under **'Nursing'** section.

Expected result:

1. A consistency should be kept. **Progress Notes** should be displayed under the same section both on SC and HB.

**Comment by tudorsss** [comment]
hey @unleu, I've added the updated bug in the above comment; please add it to youtrack, add it as a minor problem, assign it to Chirag.

**Comment by tudorsss** [comment]
Add it as a bug in the SC project, btw, @unleu.

**Comment by unleu** [comment]
not reproduced on the latest build
