### ISSUE TITLE
'Lab order' and 'Schedule Follow Up' are not available on SC

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#66]
i think they should..

**Comment by tudorsss** [comment]
Hey @unleu, you have "Schedule Next Visit" and "Lab Draw" in the patient's snapshot. Are you talking about these sections missing from the main menu?

**Comment by unleu** [comment]
@tudorsss , no, talking about Treatment ->Schedule Follow-UP and Treatment->Lab Order

**Comment by tudorsss** [comment]
OK @unleu,

Make this ticket as a bug, an inconsistency with what HB has to offer.

**Comment by unleu** [comment]
https://envoy.myjetbrains.com/youtrack/issue/SC-133
