### ISSUE TITLE
SC - Insurance is missing from the patient's record

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#67]
Steps to reproduce:

1. Login to SC with a valid nurse account and open a patient's record
2. Check if there is a Subsection Insurance under Patient section

Actual result:

2. No there is not.

Expected result:

2. Yes, there should be.

Note: Navigate to patient's Snapshot and Tap on enter Insurance Information at Primary Insurance and see if it works or tap on More button. 

There is a bug on the above note from what i remember.

**Comment by tudorsss** [comment]
Hey @unleu,

Here's the updated bug; please add it; minor priority, assign it to Chirag

Steps to reproduce:

1. Login to SC with a valid nurse account and open a patient's record;
2. Check if there is an Insurance subsection under Patient section;

Actual result:

2. No there is not.

Expected result:

2. Yes, there should be.

**Comment by tudorsss** [comment]
@unleu, btw, here's that bug from your notes: https://envoy.myjetbrains.com/youtrack/issue/SC-120

**Comment by unleu** [comment]
https://envoy.myjetbrains.com/youtrack/issue/SC-135
