### ISSUE TITLE
SC - Displaying 'Nursing Visit Notes' should not be random

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#69]
Preconditions: use a patient that has multiple 'Nursing Visit Notes'

Steps to reproduce:

1. Login to SC with a valid nurse account and open a patient's record;
2. Navigate to 'Nursing' and open 'Nursing Visit Notes' subsection;
3. Check the order the notes are displayed and then tap on 'Refresh' button multiple times and check behavior;

Actual result:

3. The list items are displayed randomly

Expected result:

3. The list items should be ordered somehow.

**Comment by tudorsss** [comment]
Hey @unleu,

I am using the patient Harold Smith with smyers/Test@1 as a nurse; I have 3 nurse visit notes, I tap on refresh but the table order remains the same. I created these forms via HB. What are we missing?

**Comment by unleu** [comment]
reproduce it on SC, on HB is ok

**Comment by unleu** [comment]
my notes are from 2 different nurses.. maybe that..let me check on another patient

**Comment by tudorsss** [comment]
Hey @unleu, I did try to reproduce it on SC and it was not happening to me. Let me know about the 2 different nurses thing.

**Comment by unleu** [comment]
it is not reproduced. I'm going to close it
