### ISSUE TITLE
HB - cannot add 'Nursing Visit Notes '

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#7]
**In relationship with SC 122**

Steps to reproduce:

1.  Login to HB with a nurse account
2. Go to 'Patients', select a patient with an active treatment
3. Go to nursing
4. Click on Nursing Visit Notes
5. Then click on 'Add new' or 'Prefill' button and check behavior

Actual result:
5. The page gets stuck trying to load the data;

Expected result:
5. The page should present the data requested.

**Comment by tudorsss** [comment]
Hey @unleu, where is that nursing section you are mentioning from step 3?

**Comment by unleu** [comment]
@tudorsss i'm talking about HB, not scout. It's in the menu

same bug as in SC is reproduced in HB

**Comment by tudorsss** [comment]
http://pm.envoymobile.com/youtrack/issue/SC-123
