### ISSUE TITLE
Schedule end at Patient Reported should be autofilled when completing Repet Every

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#70]

**Comment by tudorsss** [comment]
I'm thinking this still needs to get populated, @unleu.

**Comment by unleu** [comment]
@tudorsss populated by the user?

**Comment by tudorsss** [comment]
No, the bug description, as I am not sure what the bug is about, @unleu :P

**Comment by unleu** [comment]
I'll close this bug as the field I was talking about is OPTIONAL so the bug is not applicable anymore.
