### ISSUE TITLE
Treatment and Diagnosis are not updated automatically

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#72]
Preconditions: Use a patient with an active treatment

Steps to reproduce:

1. Login to HB with a valid admin account and a valid patient account;
2. On admin account go to Treatment/Intake subsection and edit the active treatment - save changes;
3. Change the diagnosis and the treatment of the patient - save changes;
4. Go to the patient's account and see if the information you updated on step 2 & 3 is updated in his Home Screen;

Actual result:

4 . No, it was not. It only updates upon log-out/log-in; it doesn't update if you just refresh the page.

Expected result:

4 . Should the new diagnosis and treatment be updated on the patient's Home Screen dynamically?

**Comment by tudorsss** [comment]
Hey @unleu, add it as a Low priority, 3.25.0 and assign it to Patrick. You can post it in youtrack, I updated the ticket a little.

**Comment by unleu** [comment]
https://envoy.myjetbrains.com/youtrack/issue/HB-1376
