### ISSUE TITLE
Patient's assigned nurse name is the user who created a 'Nursing visit note'

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#76]
Steps to reproduce:

1. Login to HB with a valid **admin account** and Create a **new patient**;
2. Navigate to **Treatment/Intake** subsection and create a **new Intake**;
3. Fill out the required fields and at **'Primary RN'** select a user type nurse;
4. Login with the patient and see if the nurse's name appears on the home screen;
5. Login to the admin account and navigate to **Nursing/Nursing visit notes**;
6. Create a **new nursing visit note**;
7. Login again with the patient and see if the nurse's name appears on the home screen;

Actual result:

7 . The Nurse assigned appears to be the user who created the Nursing Visit Note.

Expected result:

7 . The nurse assigned should be the one from Intake/Primary RN.

**Comment by tudorsss** [comment]
http://pm.envoymobile.com/youtrack/issue/HB-1373 @unleu, closing.
