### ISSUE TITLE
Nurse visit notes values from vital rows have no restriction

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#77]
Steps to reproduce:

1. Open a patient;s record and navigate to Nursing/Nurse visit notes
2. Add new nurse visit note and go to "Patient Encounter: Vitals"
3. Click on Add Row and see if you can fill out the fields: **Pulse (bpm), Blood Pressure, Respiration Rate (#/min)** and **Titration rate (mL/hr)** with very large numbers. 

Actual result:

3 . Yes, you can. 

Expected result:

3 . The user should not be able to type large numbers.

**Comment by tudorsss** [comment]
http://pm.envoymobile.com/youtrack/issue/HB-1374 @unleu, closing.

**Comment by tudorsss** [comment]
BTW @unleu, these types of bugs are all over the product in every form. There should be restrictions to some of the fields, but we don't have them. This is another task you can take when you run out of things to test.
