### ISSUE TITLE
SC - Taping on refresh button twice in Patient table shows the patients twice

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#81]
Steps to reproduce:

1. Login to SC with a valid nurse account that has multiple assigned patients;
2. Tap quickly on refresh button twice;
3. Check behavior;

Actual result:

3 . The patients are displayed twice on the list

Expected result:

3 . The patients should not be doubled

**Comment by tudorsss** [comment]
This still happens on the latest iPad Scout build on the iPad, but not on the Simulator; let's wait till next week and see if it still happens on a newer build.
