### ISSUE TITLE
Allergies modified on HB don't sync on SC

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#9]
Preconditions: Be sure that on SC the nurse is logged in

Steps to reproduce:

1. Login to HB with a valid user account
2. Go to a patient that has active treatment
3. Click on 'Allergies' and add a new allergy or modify an existing one
4. On SC tap on 'Menu' button and open 'Sync'
5. Tap on 'Sync' and wait for the sync to be completed
6. Open the patient record and tap on 'Refresh'
7. From 'Snapshot' tap on 'Allergies'
8. Check if the modified allergy or the newly added one is seen by the nurse

Actual result:

8. The modifications made on HB platform regarding allergies are not seen by the SC user

Expected result:

8. The modifications made on HB platform regarding allergies should be seen by the SC user

**Note 1:** This bug is still reproduced if you skip step 4, 5 and 6.
**Note 2:** After step 3 the 'Allergies' on patients 'Snapshot' are updated automatically.

**Comment by tudorsss** [comment]
Hey @unleu,

This bug doesn't happen for me; Can you take another look?

I tested with Allview Jana on test.envoymobile.net. I did see that I am able to add an allergy for the same medication twice.

**Comment by tudorsss** [comment]
http://pm.envoymobile.com/youtrack/issue/HB-1277

**Comment by unleu** [comment]
@tudorsss It is still reproduced on the iPad

**Comment by tudorsss** [comment]
Hey @unleu, this is the bug, please take a look: https://envoy.myjetbrains.com/youtrack/issue/HB-1293

**Comment by tudorsss** [comment]
Another related bug: http://pm.envoymobile.com/youtrack/issue/SC-125.

**Comment by tudorsss** [comment]
Another one: https://envoy.myjetbrains.com/youtrack/issue/SC-126; I won't be adding any more bug links to tickets, only if they are 100% match. I hope you are following them in Scout :)
