### ISSUE TITLE
HB - A username can be duplicated if you capitalize at least one of the letters

### ISSUE THREAD

**Issue by unleu** [tudorsss/Food-Tracker#98]
Preconditions: Have an active username remembered. I used 'pcoop'.

Steps to reproduce:

1. Login with an admin account to test.envoymobile.net;
2. Go to **Manage/Users** and select **Add new**;
3. Fill out the required fields and at **username** field type the username that already exists and capitalise one of its letters. I used 'pcooP';
4. Check if the information gets saved and the user is created;

Actual result:

4 Yes, the user is created.

Expected result:

4 There should not be a difference between usernames that are typeed with or without one or more upper case letters.

**Note:** You cannot login with, for example, 'Pcoop'. An error message ('Invalid username or password) is displayed.

![2016-07-12 14_03_32](https://cloud.githubusercontent.com/assets/14166590/16765214/74509a8a-483b-11e6-83c5-ef0666585f23.png)

**Comment by tudorsss** [comment]
Technically it's not the same username; letter a can be interpreted by the computer by these values, 97	141	61	01100001, while letter A by these ones: 65	101	41	01000001. Check http://www.ascii-code.com/ for reference, @unleu. I'm going to close it out.

Thanks!

**Comment by unleu** [comment]
@tudorsss I think we should ask envoy if this is a none issue.

For example, if a username is its name (paulduna) the user can type it by reflex with first letter capitalize (PaulDuna).

**Comment by tudorsss** [comment]
Hey @unleu, this is similar to the email one; here's some thoughts of other people searching for the same thing you did:

http://sqa.stackexchange.com/questions/15133/should-username-login-id-be-case-sensitive.

I'm going ask the group if they want the usernames and emails to be  case sensitive or not, though.
